### ISSUE TITLE
I don't know how to install SCIPSDP.tgz in windows. Do you mind to help me?

### ISSUE THREAD

**Issue by caulcw** [scipopt/MatlabSCIPInterface#3]
Searching for SCIP install ...
Checking environment variables SCIPOPTDIR and SCIPDIR ...
SCIP not found! Would you like to specify a custom install location? (y/n)y
Please specify SCIP directory:
Setting SCIP directory to 'C:/SCIPOptSuite 8.0.0'.

Searching for SCIPSDP install ...
Checking environment variable SCIPSDPDIR ...
SCIPSDP not found! Would you like to specify a custom install location? (y/n)y
Please specify SCIPSDP directory:
Setting SCIPSDP directory to 'C:/scipsdp-4.0.0'.

SCIP install using 'make install' or '.exe' detected.
Unrecognized function or variable 'inc'.

Error in matlabSCIPSDPInterface_install>setIncludeSCIPSDP (line 296)
if ~checkDir(inc(2:length(inc)))

Error in matlabSCIPSDPInterface_install (line 53)
[incscipsdp, sdpinstallversion] = setIncludeSCIPSDP(scipsdppath);

**Comment by pfetsch** [comment]
You first need to install SCIPSDP, following the INSTALL instructions there.

**Comment by ChengweiLou** [comment]
> 

Yes. But do you know how to install SCIPSDP in windows?

I have read their instruction. But I still have no idea.

If you don't mind, please give me some hints that how to install SCIPSDP in windows.

Thank you very much.

**Comment by pfetsch** [comment]
You first need to install SCIP, see [(url)https://scipopt.org/doc/html/md_INSTALL.php]. Since you need to compile SCIPSDP from the Source (there is no precompiled binary), the easiest is to use MinGW or the WSL (available for Windows >= 10). If you use these, the installation is similar to Linux.

**Comment by ChengweiLou** [comment]
I have tried both Windows and Linux. I think I install SCIP successfully.

But it is still hard to link SCIPSDP to SCIP.


And I follow offical 'INSTALL'

'
Building SCIP-SDP via Makefile
------------------------------
Now you are ready to install SCIP-SDP. This can be done either via Makefile (established)
or via cmake (experimental). For building via Makefile, you need to set a symbolic link to your
SCIP directory in the lib-subdirectory after unpacking the files, this can be done via

mkdir lib
cd lib
ln -s /home/username/scipoptsuite-6.0.0/scip/ scip
cd ..

if /home/username/scipoptsuite-6.0.0/scip is the path to your SCIP directory.
Afterwards you can use "make" to compile the plugin. For SCIP-SDP the option SDPS
is mandatory, it defines the SDP-solver that should be used.
'


(base) chengwei@chengwei-Latitude-5411:$ cd /home/chengwei/scipsdp-4.0.0
(base) chengwei@chengwei-Latitude-5411:/scipsdp-4.0.0$ mkdir lib
(base) chengwei@chengwei-Latitude-5411:/scipsdp-4.0.0$ cd lib
(base) chengwei@chengwei-Latitude-5411:/scipsdp-4.0.0/lib$ ln -s /home/chengwei/SCIPOptSuite-8.0.0-Linux/bin/scip
(base) chengwei@chengwei-Latitude-5411:/scipsdp-4.0.0/lib$ cd ..
(base) chengwei@chengwei-Latitude-5411:/scipsdp-4.0.0$ make
make/make.scipsdpproj:113: .//lib/scip/bin/scip... not found
make/make.scipsdpproj:114: *** Please compile SCIP with options LPS= SUFFIX= OSTYPE= ARCH= COMP= TPI=. Stop.
(base) chengwei@chengwei-Latitude-5411:~/scipsdp-4.0.0$

How can I handle this problem?

I install SCIPOptSuite-8.0.0-Linux by precompiling sh.

I think the location is right.

Thank you very much.

Best,

Chengwei

**Comment by hyMIT** [comment]
Hi, I have some questions about the matlabInterface. I could already use scip to solve the *.lp and it corresponds to my former work, And the env varibles is Done! but I cannot install the matInterface successfully.And it reports 

Searching for SCIP install ...
Checking environment variables SCIPOPTDIR and SCIPDIR ...
SCIPDIR variable found.

Could not identify src or include directory: 
Structure of specified SCIP directory 'C:/Program Files (x86)/SCIPOptSuite8.0/bin' not recognized.
SCIP not found! Would you like to specify a custom install location? (y/n)

**Comment by pfetsch** [comment]
You need to set `SCIPDIR` to the SCIP-directory within the SCIP optimization suite - something like `C:/Program Files (x86)/SCIPOptSuite8.0/scip` (do not add `bin`).

**Comment by hyMIT** [comment]
Actuallly, I give up using the matlab interface of scip. I finally finish my work using python. It's fast, clear and also efficient. Some of my mate said she succeed in working with matlab interface, while I have never seen it. So I think it may worked before, but i recommend Python. That's all.



在 2023-03-10 18:51:14，"Marc Pfetsch" ***@***.***> 写道：

Closed #3 as completed.
