### ISSUE TITLE
'display' option does not display anything

### ISSUE THREAD

**Issue by RobinKlement** [scipopt/MatlabSCIPInterface#5]
Unfortunately, changing 'display' to 'iter' or 'final' in `optiset` does not yield any output.

As an example I took "MixedInteger_LinearProgramming.m" and I ran the first example with changing the code
```
opts = optiset('display','off');
```
for
```
opts = optiset('display','iter');
```
and there is still no output to the Matlab console.

[opti_debug.txt](https://github.com/scipopt/MatlabSCIPInterface/files/11090872/opti_debug.txt)

**Comment by pfetsch** [comment]
There was an error in the implementation. I tried to fix this. Please check again.

**Comment by RobinKlement** [comment]
Unfortunately, I still see no output from SCIP or the interface at all. I tested with my own optimization problem as well as with all examples from "MixedInteger_LinearProgramming.m" (but leaving out the part `,'options',opts` because of #6.

Disclaimer: I have updated MATLABScipInterface on my machine and recompiled the mex file. The new mex file seems to be broken and Matlab freezes, leaving me with the only option of force-quitting Matlab. The same happens with the post-installation tests. Therefore I started it with the old mex file.

[opti_debug.txt](https://github.com/scipopt/MatlabSCIPInterface/files/11286118/opti_debug.txt)

**Comment by pfetsch** [comment]
I have tried to fix the other problems.

For the output to be active, you would need to recompile the Mex-interface. One issue for you might be that Matlab requires certain compiler versions for compiling mex-files. If they are not correct, the interface will not work.

If you manage to compile and still no output appears, please tell me again.

**Comment by RobinKlement** [comment]
Again, I have updated MATLABScipInterface on my machine and recompiled the mex file. Unfortunately still, when calling the newly compiled mex file via "scip", Matlab freezes, leaving me with the only option of force-quitting Matlab. The same happens with the post-installation tests.

[opti_debug.txt](https://github.com/scipopt/MatlabSCIPInterface/files/11677499/opti_debug.txt)

**Comment by pfetsch** [comment]
Can you please display the complete output after you call matlabSCIPInterface_install.m?

**Comment by RobinKlement** [comment]
Yes, of course.
[output_MATLABSCIPInterface_install.txt](https://github.com/scipopt/MatlabSCIPInterface/files/11678969/output_MATLABSCIPInterface_install.txt)

**Comment by pfetsch** [comment]
Can you please check whether https://www.mathworks.com/help/matlab/matlab_external/compiling-c-mex-files-with-mingw.html helps?
