### ISSUE TITLE
error with installing

### ISSUE THREAD

**Issue by ellensonny** [scipopt/MatlabSCIPInterface#8]
HI,
I run the matlabSCIPInterface_install.m and got this:
![image](https://github.com/user-attachments/assets/c32f9db0-9be8-461e-b2d7-9f262b9fa964)

![image](https://github.com/user-attachments/assets/f3ee9699-428b-4523-b199-4ac31c7c870f)

and I have made setting like this:
![image](https://github.com/user-attachments/assets/933ccffd-07e6-4f92-88db-0f40d8c4d60d)

so what i did wrong?please give some advice.thank you very much.

**Comment by pfetsch** [comment]
I think the path is wrong. You need to set the path to the scip directory, i.e., I guess to  `F:SCIPOptSuite.9.1.0/scip` or `F:SCIPOptSuite.9.1.0/scip/build` if you built SCIP using cmake in the directory `build`.

**Comment by ellensonny** [comment]
thank you for reply.sorry, i don not understand. the directory of scip is like this:
![image](https://github.com/user-attachments/assets/b440ccef-edb8-4840-954b-b632b18750c4)

would you please explain the problem in detail?

**Comment by pfetsch** [comment]
O.k. I see. 

Can you please copy the complete output from your matlab window as text to a comment, because the screenshot cuts off information on the right hand side. I would like to see the complete lines starting with `max -largArrayDims ...` and `F:\MatlabSCIPInterface-master\MatlabSCIPInterface-master\...`. 

Do you happen to know why `MatlabSCIPInterface-master` appears twice in your path?

**Comment by ellensonny** [comment]
I konw why MatlabSCIPInterface-master appears twice in my path and i fix it.

the complete output from my matlab window as text to a comment:

>> matlabSCIPInterface_install

Searching for SCIP install ...
Checking environment variables SCIPOPTDIR and SCIPDIR ...
SCIP not found! Would you like to specify a custom install location? (y/n)y
Please specify SCIP directory:
Setting SCIP directory to 'F:/SCIPOptSuite 9.1.0'.

SCIP install using 'make install' or '.exe' detected.

------------------------------------------------
SCIP MEX FILE INSTALL

MEX Call:
mex  -largeArrayDims   -DNO_CONFIG_HEADER -g scip/scipmex.cpp scip/scipeventmex.cpp scip/scipnlmex.cpp -Iscip/Include -I'F:/SCIPOptSuite 9.1.0/include' -I'F:/SCIPOptSuite 9.1.0/include/blockmemshell' -Iopti  -IInclude -L'F:/SCIPOptSuite 9.1.0/lib/' -lscip  -L'E:\\matlab2023a\extern\lib\win64\mingw64' -lut  -output scip -DML_VER=R2023a -DOPTI_VER=3.00

使用 'MinGW64 Compiler (C++)' 编译。
F:\MatlabSCIPInterface-master\Source\scip\scipnlmex.cpp:69:8: warning: 'double addNonlinearCon(SCIP*, SCIP_VAR**, double*, size_t, double, double, double*, size_t, bool)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 double addNonlinearCon(
        ^~~~~~~~~~~~~~~

Done!
Error Compiling SCIP!
C:\Users\HP\AppData\Local\Temp\mex_1554027202625729_41084\scipmex.obj: In function `mexFunction':
F:/MatlabSCIPInterface-master/Source/scip/scipmex.cpp:749: undefined reference to `__imp__Z25SCIPincludeCtrlCEventHdlrP4Scip'
F:/MatlabSCIPInterface-master/Source/scip/scipmex.cpp:749: undefined reference to `__imp__Z25SCIPincludeCtrlCEventHdlrP4Scip'
F:/MatlabSCIPInterface-master/Source/scip/scipmex.cpp:1346: undefined reference to `__imp__Z15addNonlinearConP4ScipPP8SCIP_VarPdyddS4_yb'
F:/MatlabSCIPInterface-master/Source/scip/scipmex.cpp:1372: undefined reference to `__imp__Z15addNonlinearConP4ScipPP8SCIP_VarPdyddS4_yb'
F:/MatlabSCIPInterface-master/Source/scip/scipmex.cpp:1400: undefined reference to `__imp__Z15addNonlinearConP4ScipPP8SCIP_VarPdyddS4_yb'
collect2.exe: error: ld returned 1 exit status

------------------------------------------------
INSTALLING Matlab-SCIP Interface ...

- Checking MATLAB version and operating system ...
MATLAB (R2023a) 64bit (Windows x64) detected.

- Checking MEX file release information ...
MEX file is not compatible with this version of the Interface.
错误使用 matlabSCIPInterface_install>mexFileCheck
MEX file incompatible.

出错 matlabSCIPInterface_install (第 88 行)
if (~mexFileCheck(localVer))
 
>> 

and the matlab window is like this:
![image](https://github.com/user-attachments/assets/9af3628d-22b9-4306-aa27-fd0a06885974)

**Comment by pfetsch** [comment]
I am not sure about this one. One possibility is that MinGW has problems with `SCIP_EXPORT`. Can you please try to replace `SCIP_EXPORT` in the files `Source/scip/Include/scipnlmex.h` and `Source/scip/Include/scipeventmex.h` by `__attribute__ ((dllexport))`? If this does not work, can you try by replacing it by `extern`?

**Comment by ellensonny** [comment]
I have tried both __attribute__ ((dllexport)) and extern,but it did not work.
matlab workspace like this:

>> matlabSCIPInterface_install

Searching for SCIP install ...
Checking environment variables SCIPOPTDIR and SCIPDIR ...
SCIP not found! Would you like to specify a custom install location? (y/n)y
Please specify SCIP directory:
Setting SCIP directory to 'F:/SCIPOptSuite 9.1.0'.

SCIP install using 'make install' or '.exe' detected.

------------------------------------------------
SCIP MEX FILE INSTALL

MEX Call:
mex  -largeArrayDims   -DNO_CONFIG_HEADER -g scip/scipmex.cpp scip/scipeventmex.cpp scip/scipnlmex.cpp -Iscip/Include -I'F:/SCIPOptSuite 9.1.0/include' -I'F:/SCIPOptSuite 9.1.0/include/blockmemshell' -Iopti  -IInclude -L'F:/SCIPOptSuite 9.1.0/lib/' -lscip  -L'E:\\matlab2023a\extern\lib\win64\mingw64' -lut  -output scip -DML_VER=R2023a -DOPTI_VER=3.00

使用 'MinGW64 Compiler (C++)' 编译。
F:\MatlabSCIPInterface-master\Source\scip\scipnlmex.cpp:69:8: warning: 'double addNonlinearCon(SCIP*, SCIP_VAR**, double*, size_t, double, double, double*, size_t, bool)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 double addNonlinearCon(
        ^~~~~~~~~~~~~~~

Done!
Error Compiling SCIP!
C:\Users\HP\AppData\Local\Temp\mex_2124451503261630_19568\scipmex.obj: In function `mexFunction':
F:/MatlabSCIPInterface-master/Source/scip/scipmex.cpp:1346: undefined reference to `__imp__Z15addNonlinearConP4ScipPP8SCIP_VarPdyddS4_yb'
F:/MatlabSCIPInterface-master/Source/scip/scipmex.cpp:1372: undefined reference to `__imp__Z15addNonlinearConP4ScipPP8SCIP_VarPdyddS4_yb'
F:/MatlabSCIPInterface-master/Source/scip/scipmex.cpp:1400: undefined reference to `__imp__Z15addNonlinearConP4ScipPP8SCIP_VarPdyddS4_yb'
collect2.exe: error: ld returned 1 exit status

------------------------------------------------
INSTALLING Matlab-SCIP Interface ...

- Checking MATLAB version and operating system ...
MATLAB (R2023a) 64bit (Windows x64) detected.

- Checking MEX file release information ...
MEX file is not compatible with this version of the Interface.
错误使用 matlabSCIPInterface_install>mexFileCheck
MEX file incompatible.

出错 matlabSCIPInterface_install (第 88 行)
if (~mexFileCheck(localVer))
 
>>

**Comment by pfetsch** [comment]
It seems that we make progress, since the other objects (in `scipeventmex.h`) seem to have disappeared.

You could try the following: In `scipnlmex.cpp` there is a line that is commented out. Can you put it back in:
` #define SCIP_EXPORT __attribute__((visibility("default")))`.
Hopefully, this will resolve the issue.

**Comment by ellensonny** [comment]
does this mean it work? here is the workspace:

matlabSCIPInterface_install

Searching for SCIP install ...
Checking environment variables SCIPOPTDIR and SCIPDIR ...
SCIP not found! Would you like to specify a custom install location? (y/n)y
Please specify SCIP directory:
Setting SCIP directory to 'F:/SCIPOptSuite 9.1.0'.

SCIP install using 'make install' or '.exe' detected.

------------------------------------------------
SCIP MEX FILE INSTALL

MEX Call:
mex  -largeArrayDims   -DNO_CONFIG_HEADER -g scip/scipmex.cpp scip/scipeventmex.cpp scip/scipnlmex.cpp -Iscip/Include -I'F:/SCIPOptSuite 9.1.0/include' -I'F:/SCIPOptSuite 9.1.0/include/blockmemshell' -Iopti  -IInclude -L'F:/SCIPOptSuite 9.1.0/lib/' -lscip  -L'E:\\matlab2023a\extern\lib\win64\mingw64' -lut  -output scip -DML_VER=R2023a -DOPTI_VER=3.00

使用 'MinGW64 Compiler (C++)' 编译。
In file included from F:\MatlabSCIPInterface-master\Source\scip\scipmex.cpp:21:
scip\Include/scipnlmex.h:13: warning: "SCIP_EXPORT" redefined
 #define SCIP_EXPORT __attribute__((visibility("default")))
 
In file included from F:\SCIPOptSuite 9.1.0\include/scip/def.h:52,
                 from F:\SCIPOptSuite 9.1.0\include/scip/scip.h:44,
                 from F:\MatlabSCIPInterface-master\Source\scip\scipmex.cpp:16:
F:\SCIPOptSuite 9.1.0\include/scip/scip_export.h:15: note: this is the location of the previous definition
 #      define SCIP_EXPORT __declspec(dllimport)
 

In file included from F:\MatlabSCIPInterface-master\Source\scip\scipnlmex.cpp:19:
scip\Include/scipnlmex.h:13: warning: "SCIP_EXPORT" redefined
 #define SCIP_EXPORT __attribute__((visibility("default")))
 
In file included from F:\SCIPOptSuite 9.1.0\include/scip/def.h:52,
                 from F:\MatlabSCIPInterface-master\Source\scip\scipnlmex.cpp:16:
F:\SCIPOptSuite 9.1.0\include/scip/scip_export.h:15: note: this is the location of the previous definition
 #      define SCIP_EXPORT __declspec(dllimport)
 

MEX 已成功完成。
Done!

------------------------------------------------
INSTALLING Matlab-SCIP Interface ...

- Checking MATLAB version and operating system ...
MATLAB (R2023a) 64bit (Windows x64) detected.

- Checking MEX file release information ...
MEX files match interface release.

Would you like to run post installation tests? (Recommended) (y/n): y

Checking OPTI Toolbox Installation:
Checking    LP Solver Results...  scip  1  2  3  4  5 Ok
Checking  MILP Solver Results...  scip  1  2  3  4  5 Ok
Checking    QP Solver Results...  scip  1  2  3 Ok
Checking  MIQP Solver Results...  scip  1  2 Ok
Checking   NLP Solver Results...  scip  1  2 Ok
Checking MINLP Solver Results...  scip  1 Ok

Toolbox checked out ok! - Enjoy.


Matlab-SCIP Interface installation complete!

------------------------------------------------
MATLAB-SCIP-INTERFACE AVAILABLE SOLVERS:

SCIP:            Available      v9.1.0
SCIPSDP:         Not Available  
------------------------------------------------
To be able to use the Matlab-SCIP Interface after restarting Matlab, you need to save path changes
or add them manually every time you launch matlab (the script addPaths.m can be used to do so).
Paths can be saved using the command:
     savepath() 
If you are unable to save path changes we refer to the 'Common Problems' section in the README
or directly to the Matlab documentation.


I think that i have resolve the issue,however,when I want use scip by yalmip,i do a test .and it says "failed".
what is going on?
![image](https://github.com/user-attachments/assets/a2d63680-bcd7-4f11-a1b9-d566b9284cac)

**Comment by pfetsch** [comment]
I think it worked. 

The fail for "global nonconcex programming"  probably shows a problem with solving MINLPs. You probably need to compile SCIP with IPOPT to improve this. If you do not need to solve nonlinear problems, you can proceed with your current version.

**Comment by ellensonny** [comment]
thanks for your reply very much.

**Comment by zying0827** [comment]
Hello,

I encountered similar installation error messages.
```
>> matlabSCIPInterface_install

Searching for SCIP install ...
Checking environment variables SCIPOPTDIR and SCIPDIR ...
SCIP not found! Would you like to specify a custom install location? (y/n)y
Please specify SCIP directory:
Setting SCIP directory to '<path>/SCIPOptSuite9.2.0'.

SCIP install using 'make install' or '.exe' detected.

------------------------------------------------
SCIP MEX FILE INSTALL

MEX Call:
mex  -largeArrayDims   -DNO_CONFIG_HEADER -g scip/scipmex.cpp scip/scipeventmex.cpp scip/scipnlmex.cpp -Iscip/Include -I'<path>/SCIPOptSuite9.2.0/include' -I'<path>/SCIPOptSuite9.2.0/include/blockmemshell' -Iopti  -IInclude -L'<path>/SCIPOptSuite9.2.0/lib/' -lscip  -L'C:\\Program Files\\MATLAB\\R2024a\extern\lib\win64\mingw64' -lut  -output scip -DML_VER=R2024a -DOPTI_VER=3.00

Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Done!

------------------------------------------------
INSTALLING Matlab-SCIP Interface ...

- Checking MATLAB version and operating system ...
MATLAB (R2024a) 64bit (Windows x64) detected.

- Checking MEX file release information ...
MEX file is not compatible with this version of the Interface.
Error using matlabSCIPInterface_install>mexFileCheck (line 390)
MEX file incompatible.

Error in matlabSCIPInterface_install (line 88)
if (~mexFileCheck(localVer))
```
![螢幕擷取畫面 2024-11-25 170954](https://github.com/user-attachments/assets/60df4d50-4c1c-4675-8880-f9daa0d7e78a)

As suggested above, here are my modifications.
1. In `scipnlmex.h` and `scipeventmex.h`, replace `SCIP_EXPORT ` with `__attribute__ ((dllexport))`
2. In `scipnlmex.cpp`, uncomment `#define SCIP_EXPORT __attribute__((visibility("default")))`
![螢幕擷取畫面 2024-11-25 171030](https://github.com/user-attachments/assets/53a36c31-f544-4a14-8fdb-257e6e2790f0)
![螢幕擷取畫面 2024-11-25 171059](https://github.com/user-attachments/assets/1816d638-f701-4c72-85a8-eed174b9c1f5)

I still cannot finish the installation, are there any suggestions? Thanks in advance.
